add_rules("mode.debug", "mode.release")
add_requires("rapidjson")
add_requires("websocketpp")
add_requires("asio")
add_requires("openssl")

option("version")

target("sioclient")
    set_kind("$(kind)")
    set_languages("cxx11")
    add_files("src/*.cpp")
    add_files("src/internal/*.cpp")
    add_headerfiles("src/internal/*.h")
    add_headerfiles("src/*.h")
    add_packages("rapidjson", "websocketpp", "asio", "openssl")
    add_defines("VERSION=\"$(version)\"")
