package("diasdk")
    set_homepage("https://visualstudio.microsoft.com/")
    set_description("The Microsoft Debug Interface Access (DIA) SDK provides access to debug information stored in program database (.pdb) files generated by Microsoft postcompiler tools.")

    on_fetch("windows|x86", "windows|x64", "windows|arm", "windows|arm64", function (package, opt)
        if opt.system then
            import("detect.sdks.find_dia_sdk")

            -- Older xmake versions lack x86 and append the architecture to include/.
            local dia_sdk = find_dia_sdk(nil, {arch = package:is_arch("x86") and "x64" or package:arch(), force = true})
            if dia_sdk then
                local archdir = ({x86 = "", x64 = "amd64", arm = "arm", arm64 = "arm64"})[package:arch()]
                local includedir = path.join(dia_sdk.sdkdir, "include")
                local linkdir = path.join(dia_sdk.sdkdir, "lib", archdir)
                if not os.isfile(path.join(includedir, "dia2.h")) or not os.isfile(path.join(linkdir, "diaguids.lib")) then
                    return
                end
                return {
                    includedirs = {includedir},
                    linkdirs = {linkdir, path.join(dia_sdk.sdkdir, "bin", archdir)},
                    links = {
                        package:config("shared") and "msdia140" or "diaguids"
                    }
                }
            end
        end
    end)
