name: Cross (Musl)

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [arm, aarch64]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cross-Musl-${{ matrix.cross }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Installation
        run: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      - name: Tests
        run: |
          xmake l ./scripts/test.lua -D -p cross --cross=${{ matrix.cross }}-
