name: Cross (Musl)

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [arm-unknown-linux-musleabi, aarch64-unknown-linux-musl]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cross-Musl-${{ matrix.cross }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Installation
        run: |
          wget https://github.com/musl-cross/musl-cross/releases/download/20240903/${{ matrix.cross }}.tgz
          tar -xvf ${{ matrix.cross }}.tgz

      - name: Tests
        run: |
          xmake l ./scripts/test.lua -D -p cross --toolchain=muslcc --sdk=`pwd`/${{ matrix.cross }}
