name: Cross (Musl)

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [arm-linux-gnueabihf, aarch64-linux-gnu]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cross-Musl-${{ matrix.cross }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Installation
        run: |
          wget https://github.com/24bit-xjkp/toolchains/releases/download/gcc15.0.0-v4/x86_64-linux-gnu-host-${{ matrix.cross }}-target-gcc15.tar.xz
          tar -xvf x86_64-linux-gnu-host-${{ matrix.cross }}-target-gcc15.tar.xz

      - name: Tests
        run: |
          xmake l ./scripts/test.lua -D -p cross --toolchain=muslcc --sdk=`pwd`/x86_64-linux-gnu-host-${{ matrix.cross }}-target-gcc15
