name: macOS

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'

      - name: Tests
        run: |
          wget https://curl.haxx.se/ca/cacert.pem -O /tmp/cacert.pem
          export CURL_CA_BUNDLE=/tmp/cacert.pem
          xmake l ./scripts/test.lua -D -k ${{ matrix.kind }}

