name: Monkey (macOS)

on:
  schedule: # execute every 24 hours
    - cron: "0 */24 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Tests
        run: |
          xmake l ./scripts/monkey.lua -D -k ${{ matrix.kind }}

