package("csv2")
    set_urls("https://github.com/p-ranav/csv2.git")
    set_homepage("https://github.com/p-ranav/csv2")
    set_description("A CSV parser library")
    set_license("MIT")
    add_versions("v0.1", "a20992f7a1b75215609037c4cc66f690e8691aab")
    on_install(function (package)
        os.cp("include/csv2", package:installdir("include"))
    end)
    on_test(function (package)
        assert(package:has_cxxtypes("csv2::Reader<csv2::delimiter<','>, csv2::quote_character<'\"'>, csv2::first_row_is_header<false>>", 
        {configs = {languages = "c++11"}, includes = "csv2/reader.hpp"}))
    end)
package_end()
